name: Build Fishbot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore packages
        run: nuget restore Fishbot.sln

      - name: Build solution
        run: msbuild Fishbot.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Fishbot-exe
          path: |
            **/bin/Release/**
